spring.application.name=developer-productivity-dashboard
spring.data.mongodb.uri=mongodb+srv://adimohapatra13:a9t033pF0fm0QWd4@cluster0.g6bacuk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Developer-Productivity-DB
logging.level.org.springframework.security=DEBUG
spring.security.user.enabled=false